services:
  python-compiler-service:
    container_name: python-compiler-service
    image: python-compiler-service:latest
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      - PATH_SUBMISSION=submissions
      - IMAGE_DOCKER=python-sandbox:latest
    ports:
      - "8001:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # link to host docker socket
      - submissions:/src/sandbox
  
  python-sandbox:
    container_name: python-sandbox
    image: python-sandbox:latest 
    build:
      context: .
      dockerfile: Dockerfile.sandbox
    working_dir: /sandbox
    command: python --version


volumes:
  submissions:
    name: submissions
