name: Python Service Docker 

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker Image 
        run: | 
          docker build -t python-sandbox:latest -f Dockerfile.sandbox . 
          docker build -t python-compiler-service:latest -f Dockerfile.app . 

      - name: Run container python-sandbox
        run:  |
          docker run --name python-sandbox python-sandbox

      - name: Run container python-compiler-service 
        run: |
          docker run -d \
            --name python-compiler-service \
            --env PATH_SUBMISSION=submissions \
            --env IMAGE_DOCKER=python-sandbox:latest \
            -p 8001:8000 \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v submissions:/src/sandbox \
            python-compiler-service:latest 
        
      - name: Verify container python-compiler-service is running
        run: |
          docker ps | grep python-compiler-service
      
      - name: Wait container start finish
        run: |
          sleep 10
      
      - name: Run test run code on vm
        run: |
          curl -X GET http://localhost:8001/python-compiler-service/sandbox/test-code-vm || exit 1
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag python-sandbox:latest ${{ secrets.DOCKER_USERNAME }}/python-sandbox:latest
          docker tag python-compiler-service:latest ${{ secrets.DOCKER_USERNAME }}/python-compiler-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/python-sandbox:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/python-compiler-service:latest