name: Python Service Docker 

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      
      - name: Build docker image python-sandbox
        run: /
          docker build -t python-sandbox:latest -f Dockerfile.sandbox . 

      - name: Build docker image python-compiler-service
        run: /
          docker build -t python-compiler-service:latest -f Dockerfile.app . 

      - name: Test run container python-sandbox
        run: /
          docker run -d python-sandbox

      - name: Wait for container to start
        run: |
          sleep 10  # หน่วงเวลา 10 วินาที เพื่อให้แน่ใจว่า container เริ่มทำงานเสร็จ

      # - name: Test container 
      #   run: |
      #     curl -s http://localhost:8080
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image python-sandbox
        run: |
          docker tag python-sandbox:latest ${{ secrets.DOCKER_USERNAME }}/python-sandbox:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/python-sandbox:latest